const CACHE="barcode-battle-v420-monster-overhaul-lite";
const ASSETS=[
  "./",
  "./index.html",
  "./manifest.webmanifest",
  "./css/v2-battle.css",
  "./js/v2-battle-ui.js",
  "./data/art-manifest.json",
  "./data/art-manifest-v30.json",
  "./data/battle-config.json",
  "./assets/monsters/beast.png",
  "./assets/monsters/bird.png",
  "./assets/monsters/dragon.png",
  "./assets/monsters/ghost.png",
  "./assets/monsters/knight.png",
  "./assets/monsters/machine.png",
  "./assets/monsters/slime.png",
  "./assets/monsters/v42/rabi.png",
  "./assets/monsters/v42/dragon.png",
  "./assets/monsters/v42/beast.png",
  "./assets/monsters/v42/bird.png",
  "./assets/monsters/v42/ghost.png",
  "./assets/monsters/v42/machine.png",
  "./assets/monsters/v42/knight.png",
  "./assets/monsters/v42/slime.png"
];
self.addEventListener("install",e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS)).then(()=>self.skipWaiting())));
self.addEventListener("activate",e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener("fetch",e=>e.respondWith(caches.match(e.request).then(r=>r||fetch(e.request))));
