const CACHE="barcode-battle-v20";
const ASSETS=[
"./","./index.html","./manifest.webmanifest",
"./assets/icon-192.png","./assets/icon-512.png","./assets/apple-touch-icon.png","./assets/icon-1024.png",
"./assets/monsters/slime.png","./assets/monsters/dragon.png","./assets/monsters/beast.png","./assets/monsters/bird.png","./assets/monsters/ghost.png","./assets/monsters/machine.png","./assets/monsters/knight.png",
"./assets/backgrounds/arena/arena.jpg","./assets/backgrounds/grassland/grassland.jpg","./assets/backgrounds/forest/forest.jpg","./assets/backgrounds/ruins/ruins.jpg","./assets/backgrounds/castle/castle.jpg",
"./assets/effects/slash/slash_blue.png","./assets/effects/fire/fire_red.png","./assets/effects/poison/poison.png","./assets/effects/lightning/lightning.png"
,"./assets/monsters/v19/legendary/beast.png","./assets/monsters/v19/legendary/bird.png","./assets/monsters/v19/legendary/dragon.png","./assets/monsters/v19/legendary/ghost.png","./assets/monsters/v19/legendary/knight.png","./assets/monsters/v19/legendary/machine.png","./assets/monsters/v19/legendary/rabi.png","./assets/monsters/v19/legendary/slime.png","./assets/monsters/v19/mythic/beast.png","./assets/monsters/v19/mythic/bird.png","./assets/monsters/v19/mythic/dragon.png","./assets/monsters/v19/mythic/ghost.png","./assets/monsters/v19/mythic/knight.png","./assets/monsters/v19/mythic/machine.png","./assets/monsters/v19/mythic/rabi.png","./assets/monsters/v19/mythic/slime.png","./assets/monsters/v19/normal/beast_1.png","./assets/monsters/v19/normal/beast_2.png","./assets/monsters/v19/normal/beast_3.png","./assets/monsters/v19/normal/bird_1.png","./assets/monsters/v19/normal/bird_2.png","./assets/monsters/v19/normal/bird_3.png","./assets/monsters/v19/normal/dragon_1.png","./assets/monsters/v19/normal/dragon_2.png","./assets/monsters/v19/normal/dragon_3.png","./assets/monsters/v19/normal/ghost_1.png","./assets/monsters/v19/normal/ghost_2.png","./assets/monsters/v19/normal/ghost_3.png","./assets/monsters/v19/normal/knight_1.png","./assets/monsters/v19/normal/knight_2.png","./assets/monsters/v19/normal/knight_3.png","./assets/monsters/v19/normal/machine_1.png","./assets/monsters/v19/normal/machine_2.png","./assets/monsters/v19/normal/machine_3.png","./assets/monsters/v19/normal/rabi_1.png","./assets/monsters/v19/normal/rabi_2.png","./assets/monsters/v19/normal/rabi_3.png","./assets/monsters/v19/normal/slime_1.png","./assets/monsters/v19/normal/slime_2.png","./assets/monsters/v19/normal/slime_3.png","./assets/monsters/v19/rare/beast.png","./assets/monsters/v19/rare/bird.png","./assets/monsters/v19/rare/dragon.png","./assets/monsters/v19/rare/ghost.png","./assets/monsters/v19/rare/knight.png","./assets/monsters/v19/rare/machine.png","./assets/monsters/v19/rare/rabi.png","./assets/monsters/v19/rare/slime.png"
,"./css/v2-battle.css","./js/v2-battle-ui.js","./data/art-manifest.json","./data/battle-config.json"
];
self.addEventListener("install",e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS)).then(()=>self.skipWaiting())));
self.addEventListener("activate",e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener("fetch",e=>e.respondWith(caches.match(e.request).then(r=>r||fetch(e.request))));
